### ISSUE TITLE
callback not called?

### ISSUE THREAD

**Issue by chiester** [gfk-ba/meteor-mailgun-api#5]
I'm doing: 

```
myEmail.send(emailObject, function(error, body) {
console.log(body)
})
```
but it appears that this callback is never called? 

The email object is valid and the email is sent. 

Am I missing something?

**Comment by marcodejongh** [comment]
@chiester This package wraps around fibers around the mailgun-js package's send method so you don't need to specify a callback.

Fibers are Meteor's preferred way of preventing callback soup. In a nutshell when you use a fiber it will move the stack out of the event loop until the used fiber yields at which point it's put back into the eventloop. So even though the code is asynchronous you can program it in a synchronous way.

You can find more information about fibers [here](https://meteorhacks.com/fibers-eventloop-and-meteor)

**Comment by chiester** [comment]
Do I need to do anything special to make sure email is actually sent before executing the next line of code (the thing that is dependent on send() completing successfully)? If I want to find out if there was an error, do I just wrap it in a try/catch? (I am somewhat familiar with Fibers and in other parts of my app I have defined a Future then a wait() on the return value when I have to do an async API call.)

**Comment by marcodejongh** [comment]
@chiester Nothing special. Fiber.wait is called inside the package so no need to do that in your code. 

If ```result.errors``` has items in it there where errors while trying to sent the email.

**Comment by chiester** [comment]
Thanks for the package and for your help. You can close this question.
