### ISSUE TITLE
mailgun-js version needs to be bumped up to 0.7.7

### ISSUE THREAD

**Issue by mr-rob0to** [gfk-ba/meteor-mailgun-api#6]
Old code is point to /v2 as the endpoint.  Looks like latest version of mailgun-js npm module is pointing to /v3.  Need to have this bumped up in package.json.  Getting 404 when calling send method.

**Comment by T-Grave** [comment]
Can confirm. Running into the same problem.

**Comment by ameesters** [comment]
bumped it
